---
version: 2.1

orbs:
  ruby: circleci/ruby@1.1.3
  iora-deploy: iorahealth/iora-deployment@1.3.1

workflows:
  test:
    unless:
      equal: [master, << pipeline.git.branch >>]
    jobs:
    - changelog_check
    - minitest
  tag-release:
    when:
      equal: [master, << pipeline.git.branch >>]
    jobs:
    - iora-deploy/github-release-gem:
        context:
        - deployer-secrets

jobs:
  changelog_check:
    docker:
      - image: cimg/ruby:2.7.1
    resource_class: small
    steps:
    - checkout
    - run: |
        version=$(ruby -I. -rlib/data_uri/uri -e 'puts URI::Data::VERSION')
        if ! grep "\- v${version}" CHANGELOG.md > /dev/null; then
          echo Version ${version} does not appear to have a CHANGELOG entry. Please add one.
          exit 1
        fi

  minitest:
    docker:
    - image: cimg/ruby:3.2.2
    resource_class: small
    steps:
    - checkout
    - ruby/install-deps
    - run: bundle exec rake
